import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface RequestBody {
  message: string
  sessionId: string
  fileId?: string
  extractedText?: string
  difficulty?: string
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { message, sessionId, fileId, extractedText, difficulty = 'normal' }: RequestBody = await req.json()

    if (!message || !sessionId) {
      return new Response(
        JSON.stringify({ error: 'Message and sessionId are required' }),
        { 
          status: 400, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    // Get OpenAI API key from environment
    const openaiApiKey = Deno.env.get('OPENAI_API_KEY')
    if (!openaiApiKey) {
      return new Response(
        JSON.stringify({ error: 'OpenAI API key not configured' }),
        { 
          status: 500, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    // Create Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Get file context if fileId is provided
    let context = extractedText || ''
    
    if (fileId) {
      const { data: file, error: fileError } = await supabase
        .from('uploaded_files')
        .select('*')
        .eq('id', fileId)
        .single()

      if (!fileError && file) {
        context = file.extracted_text || ''
      }
    }

    // If no context from file, try to get from session
    if (!context) {
      const { data: session, error: sessionError } = await supabase
        .from('sessions')
        .select('*, uploaded_files(*)')
        .eq('id', sessionId)
        .single()

      if (!sessionError && session) {
        context = session.uploaded_files?.extracted_text || ''
      }
    }
    
    // Create system prompt based on difficulty
    const difficultyPrompts = {
      easy: 'あなたは親切で分かりやすい学習アシスタントです。基本的な質問から始めて、段階的に理解を深められるようにサポートしてください。',
      normal: 'あなたは優秀な学習アシスタントです。学習者の理解度を確認しながら、適切な質問で深い理解を促進してください。',
      hard: 'あなたは高度な学習アシスタントです。学習者の思考を深め、批判的思考を促進する質問をしてください。'
    }

    const systemPrompt = `${difficultyPrompts[difficulty as keyof typeof difficultyPrompts]}

学習資料の内容:
${context}

あなたの役割:
1. 学習者の回答に対して適切な質問を投げかける
2. 理解を深めるための追加の質問をする
3. 必要に応じて補足説明を提供する
4. 学習者の思考を促進する

学習者の回答: ${message}

上記の回答に対して、学習を促進する質問やコメントを返してください。`

    // Call OpenAI API
    const openaiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: systemPrompt
          }
        ],
        max_tokens: 500,
        temperature: 0.7,
      }),
    })

    if (!openaiResponse.ok) {
      const errorData = await openaiResponse.text()
      console.error('OpenAI API error:', errorData)
      return new Response(
        JSON.stringify({ error: 'Failed to generate AI response' }),
        { 
          status: 500, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    const openaiData = await openaiResponse.json()
    const aiResponse = openaiData.choices[0].message.content

    // Save AI response to database
    const { data: savedMessage, error: saveError } = await supabase
      .from('messages')
      .insert({
        session_id: sessionId,
        role: 'assistant',
        message: aiResponse,
        audio_url: null, // Will be generated by another function
      })
      .select()
      .single()

    if (saveError) {
      console.error('Error saving message:', saveError)
      return new Response(
        JSON.stringify({ error: 'Failed to save message' }),
        { 
          status: 500, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    return new Response(
      JSON.stringify({ 
        message: aiResponse,
        messageId: savedMessage.id,
        success: true 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )

  } catch (error) {
    console.error('Error:', error)
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )
  }
}) 